---
# tasks file for php

- name: Installing PHP
  yum:
   name: 
    - php 
    - php-mysql 
   state: latest

- name: Copying your php file in the /var/www/html
  copy:
   src: "/home/ubuntu/show.php" 
   dest: /var/www/html/show.php
  notify:
     - restart apache service
